# Configuration file for admin-service
server:
  port: 8000
spring:
  application:
    name: doctor-service
  datasource:
    username: root
    password: Ashish123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/appointment
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
  logging:
    level:
      sql: info
      root: info
  eureka:
    client:
      register-with-eureka: true
      fetch-registry: false
      service-url:
        defaultZone: http://localhost:8761/eureka/